# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

paginate_per_category: true

# Setup
title:            Mitch Keenan
tagline:          'Software Engineer'
description:      'Software Engineer'
url:              https://mitchkeenan.com
baseurl:          /

resume:           #
author:
  name:           'Mitch Keenan'
  url:            https://mitchkeenan.com
  email:          mail@mitchkeenan.com

version: 0.1

paginate:         5
paginate_path:    /posts/page:num/

repository:       konamacona/konamacona.github.io
gist:
  noscript: false
github: [metadata]

plugins:
  - jekyll-feed

exclude: ['Gemfile', 'Gemfile.lock', 'LICENSE.md', 'README.md', 'CNAME', '.gitignore', '_config.yml']
